server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3366/nblog
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6779

logging:
  level:
    club.la0shu5: debug